bind 0.0.0.0
protected-mode yes
port 6379
timeout 300
tcp-keepalive 300

user default off

maxmemory 512mb
maxmemory-policy allkeys-lru
maxmemory-samples 5

appendonly yes
appendfsync everysec
appendfilename "appendonly.aof"
dir /data
save 60 1000
dbfilename dump.rdb

rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command CONFIG ""
rename-command DEBUG ""

daemonize no
loglevel notice
logfile ""
databases 16
